packages:
  - "api"
  - "web"
allowBuilds:
  '@parcel/watcher': false
  '@prisma/client': false
  '@prisma/engines': false
  '@scarf/scarf': true
  bcrypt: false
  prisma: false
  sharp: true
  unrs-resolver: true
